services:
  postgres: #database container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:  
      - "5432:5432"
    networks:
      - mynetwork

  backend: #backend container
    image: backend:dev
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@postgres:5432/postgres 
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  frontend: #frontend container
    image: frontend:dev
    ports:
      - "5173:5173"    
    depends_on:
      - backend 
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
